### ajout test d'un groupe
POST http://localhost:8080/api/groupe
content-type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": "1",
  "name": "Judas Priest"
}

### get the groupe with the id 1
GET http://localhost:8080/api/groupe/1
content-type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### ajout test d'un groupe
POST http://localhost:8080/api/groupe
content-type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": "2",
  "name": "Sortilège"
}

### get all Groupe
GET http://localhost:8080/api/groupe
content-type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### adding version
POST http://localhost:8080/api/version
content-type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": "1",
  "name": "CD"
}

### get the version with the id 1
GET http://localhost:8080/api/version/1
content-type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### adding version
POST http://localhost:8080/api/version
content-type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": "2",
  "name": "vinyl"
}

### get all verion
GET http://localhost:8080/api/version
content-type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### add a genre with id 1
POST http://localhost:8080/api/genre
content-type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": "1",
  "name": "Metal"
}

### get the genre with the id 1
GET http://localhost:8080/api/genre/1
content-type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### add a genre with id 2
POST http://localhost:8080/api/genre
content-type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": "2",
  "name": "Rock"
}

### get all genre
GET http://localhost:8080/api/genre
content-type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### get all users
GET http://localhost:8080/api/users
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/json

### add user with id 1
POST http://localhost:8080/api/users
content-type: application/json
Authorization: Basic YWRtaW46YWRtaW4= // base64 de admin:admin

{
  "id": "2",
  "username": "Angel",
  "email": "luidjy.aubel@gmail.com",
  "picture": "#",
  "password": "admin",
  "role": "ADMIN"
}

### get with the user 2
GET http://localhost:8080/api/users
Authorization: QW5nZWw6YWRtaW4=
Content-Type: application/json

### get album
GET http://localhost:8080/api/albums
Authorization: QW5nZWw6YWRtaW4=
Content-Type: application/json

### add album
POST http://localhost:8080/api/albums
Authorization: QW5nZWw6YWRtaW4=
Content-Type: application/json

{
  "id": "1",
  "name": "Painkiller",
  "groupe": {
    "id": "1",
    "name": "Metal"
  },
  "release": "1990",
  "version": [{
    "id": "1",
    "name": "CD"
  }]
}

### add user with id 3
POST http://localhost:8080/api/users
content-type: application/json
Authorization: Basic YWRtaW46YWRtaW4= // base64 de admin:admin

{
  "id": "3",
  "username": "Glenn Tipton",
  "email": "glenn.tipton@jmail.com",
  "picture": "#",
  "password": "admin",
  "albums": [{
    "id": "1",
    "name": "Painkiller",
    "groupe": {
      "id": "1",
      "name": "Metal"
    },
    "release": "1990",
    "version": [{
      "id": "1",
      "name": "CD"
    }]
  }],
  "role": "ADMIN"
}